### ISSUE TITLE
Set root dir when used within a mono repo context

### ISSUE THREAD

**Issue by carbontwelve** [ferdinandfrank/cdk-nuxt#2]
Hey, I am wanting to use this stack in my monorepo which has the following structure:

```tree 
.
├── README.md
├── project-a
├── project-b
├── project-c
├── lerna.json
├── node_modules
├── package.json
├── packages
├── stack
│   ├── functions
│   ├── index.ts
│   ├── node_modules
│   ├── package.json
│   ├── src
│   ├── stacks
│   ├── tsconfig.json
│   └── types.ts
└── yarn.lock
```

As you can see the stacks are in their own folder in the root while each project being deployed has their own root folder (e.g project-a, project-b, ...)

Your nuxt stack assumes its running from the root of the repository and I would like to be able to define that. Currently my other stacks have this set as a `rootSrc` which I pass to a projects stack via `join(resolve(__dirname, '..'), 'project-a')`

May I suggest adding a `rootSrc` value to `NuxtAppStackProps` which is then used in place of `.` for the root directory? I believe this would be a small change to the `createAppLambdaFunction`, `getNuxtAppStaticAssetConfigs`, `getNuxtAppBuildAssetConfigs` and `getNuxtAppCustomAssetConfigs` functions. For example:

```ts
// Modify to use rootDir
private createAppLambdaFunction(props: NuxtServerAppStackProps): Function {
    const funcName = `${this.resourceIdPrefix}-app-function`;

    return new Function(this, funcName, {
        // snip
        code: Code.fromAsset(`${props.rootDir ?? '.' }/.output/server`, {

}

// Modify to add rootDir attribute
export const getNuxtAppStaticAssetConfigs = (srcDir: string|undefined = undefined, rootDir: string|undefined = undefined): StaticAssetConfig[] => {
    return [...getNuxtAppBuildAssetConfigs(rootDir ?? '.'), ...getNuxtAppCustomAssetConfigs(srcDir, rootDir ?? '.')];
};

// Modify to use rootDir attribute in place of .
const getNuxtAppBuildAssetConfigs = (rootDir: string): StaticAssetConfig[] => {

    // The build assets required for CSR that are generated by 'nuxt build'
    const buildAssetsSourcePath = `${rootDir}/.output/public/_nuxt`;
}

// Modify to use rootDir attribute in place of .
const getNuxtAppCustomAssetConfigs = (srcDir: string|undefined = undefined, rootDir: string|undefined = undefined): StaticAssetConfig[] => {

    // We copy the custom assets from the source directory to prevent overriding the build assets cache behavior
    // when copying from outputs directory
    const customAssetsSourcePath = `${rootDir}${srcDir ? `/${srcDir}` : ''}/public`;
}
```

**Comment by ferdinandfrank** [comment]
@carbontwelve Thank you for the suggestion! I just added a `rootDir` prop as suggested in `v1.1.0`. 😊
Feel free to open PRs in the future if you have any further improvements.
