### ISSUE TITLE
Issue with deploying to AWS

### ISSUE THREAD

**Issue by dpetrovaliev** [ferdinandfrank/cdk-nuxt#4]
Hey, I encountered issues with my initial deployment to AWS. I encountered some errors, but unfortunately, I didn't save them. However, the suggested error message from CDK was to run cdk bootstrap first and then cdk deploy. After running these commands, everything worked perfectly.

**Comment by ferdinandfrank** [comment]
@dpetrovaliev Thank you for this hint! I missed it in the docs since bootstrapping is only required once per account and region.
I just added it to the "Deployment" section of the readme.
