### ISSUE TITLE
Error: At least one header to allow must be provided

### ISSUE THREAD

**Issue by carbontwelve** [ferdinandfrank/cdk-nuxt#8]
When using the default config that includes `allowHeaders: []` it will error out with the following:

```
/xxx/node_modules/aws-cdk-lib/aws-cloudfront/lib/cache-policy.ts:241
      throw new Error('At least one header to allow must be provided');
            ^
Error: At least one header to allow must be provided
    at Function.allowList (/xxx/node_modules/cdk-nuxt/node_modules/aws-cdk-lib/aws-cloudfront/lib/cache-policy.ts:241:13)
    at NuxtServerAppStack.createNuxtAppCachePolicy (/xxx/node_modules/cdk-nuxt/lib/stack/server/NuxtServerAppStack.ts:424:70)
```

After looking at the source `NuxtServerAppStack.ts:424:70` it becomes apparent this is a configuration error, and is fixed by removing `allowHeaders: []` from my config. 

However, this is poor DX and I would suggest modifying the behaviour so that `props.allowHeaders` being `undefined` behaves the same as it being an empty array. I'll try to provide a PR shortly.

**Comment by ferdinandfrank** [comment]
@carbontwelve You are right, thank you. I'll integrate it with the next improvements. But feel free to submit a PR, if you are already working on it.
